name: SELE App Backend Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Build project
      - name: Build project
        run: yarn run build

      # Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          # host: ${{ secrets.SERVER_HOST }}
          # username: ${{ secrets.SERVER_USERNAME }}
          # key: ${{ secrets.SERVER_SSH_KEY }}
          # port: ${{ secrets.SERVER_PORT }}
          host: 69.62.67.125
          username: root
          key: ${{ secrets.TT }}
          port: 22
          script: |
            cd /var/www/SELE/backend
            git pull origin main
            yarn install
            yarn run build
            pm2 restart server
